name: Open a PR to main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  MESSAGE: Merge branch `${{ github.head_ref || github.ref_name }}` to `main`

jobs:
  pull-request:
    name: Open pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Draft Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: 'chore: ${{ env.MESSAGE }}'
          PR_BODY: |
            This pull request will ${{ env.MESSAGE }}.

            ## Before merging this PR

            - [ ] Check if the Pylint score is 10/10 🐍
            - [ ] Verify if the multi-tier downloader runs correctly 📥
            - [ ] Ensure options.json injection works ⚙️
        run: |
          # Check if a PR from the current branch to main already exists
          PR_EXISTS=$(gh pr list --base main --head ${{ github.ref_name }} --json number -q '.[0].number')
          
          # If no PR exists, create a new draft PR
          if [ -z "$PR_EXISTS" ] || [ "$PR_EXISTS" == "null" ]; then
            gh pr create \
              --base main \
              --head ${{ github.ref_name }} \
              --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --draft
            echo "Draft Pull Request created successfully! 🚀"
          else
            # If a PR already exists, skip creation
            echo "Pull Request already exists: #$PR_EXISTS. Skipping creation."
          fi
