name: 🚀 Rushiranpise Ecosystem Patcher

on:
  workflow_dispatch:
    inputs:
      app_1_1_1_1:
        description: 'Patch 1-1-1-1'
        required: true
        type: boolean
        default: false
      app_accubattery:
        description: 'Patch accubattery'
        required: true
        type: boolean
        default: false
      app_accuweather:
        description: 'Patch accuweather'
        required: true
        type: boolean
        default: false
      app_adobe_scan:
        description: 'Patch adobe-scan'
        required: true
        type: boolean
        default: false
      app_aida64:
        description: 'Patch aida64'
        required: true
        type: boolean
        default: false
      app_amoledpix:
        description: 'Patch amoledpix'
        required: true
        type: boolean
        default: false
      app_ampere:
        description: 'Patch ampere'
        required: true
        type: boolean
        default: false
      app_anime_depth:
        description: 'Patch anime-depth'
        required: true
        type: boolean
        default: false
      app_apkmirror_installer:
        description: 'Patch apkmirror-installer'
        required: true
        type: boolean
        default: false
      app_calm:
        description: 'Patch calm'
        required: true
        type: boolean
        default: false
      app_canva:
        description: 'Patch canva'
        required: true
        type: boolean
        default: false
      app_colornote:
        description: 'Patch colornote'
        required: true
        type: boolean
        default: false
      app_cpu_z:
        description: 'Patch cpu-z'
        required: true
        type: boolean
        default: false
      app_electron:
        description: 'Patch electron'
        required: true
        type: boolean
        default: false
      app_hola_vpn:
        description: 'Patch hola-vpn'
        required: true
        type: boolean
        default: false
      app_http_sniffer:
        description: 'Patch http-sniffer'
        required: true
        type: boolean
        default: false
      app_inure:
        description: 'Patch inure'
        required: true
        type: boolean
        default: false
      app_kahoot:
        description: 'Patch kahoot'
        required: true
        type: boolean
        default: false
      app_kinemaster:
        description: 'Patch kinemaster'
        required: true
        type: boolean
        default: false
      app_lark_player:
        description: 'Patch lark-player'
        required: true
        type: boolean
        default: false
      app_life360:
        description: 'Patch life360'
        required: true
        type: boolean
        default: false
      app_ml_manager:
        description: 'Patch ml-manager'
        required: true
        type: boolean
        default: false
      app_mobioffice:
        description: 'Patch mobioffice'
        required: true
        type: boolean
        default: false
      app_netguard:
        description: 'Patch netguard'
        required: true
        type: boolean
        default: false
      app_network_guru:
        description: 'Patch network-guru'
        required: true
        type: boolean
        default: false
      app_ninja_vpn:
        description: 'Patch ninja-vpn'
        required: true
        type: boolean
        default: false
      app_proton_vpn:
        description: 'Patch proton-vpn'
        required: true
        type: boolean
        default: false
      app_proxyman:
        description: 'Patch proxyman'
        required: true
        type: boolean
        default: false
      app_psiphon_pro:
        description: 'Patch psiphon-pro'
        required: true
        type: boolean
        default: false
      app_rar:
        description: 'Patch rar'
        required: true
        type: boolean
        default: false
      app_sd_maid_se:
        description: 'Patch sd-maid-se'
        required: true
        type: boolean
        default: false
      app_stargazing_hub:
        description: 'Patch stargazing-hub'
        required: true
        type: boolean
        default: false
      app_stickerly:
        description: 'Patch stickerly'
        required: true
        type: boolean
        default: false
      app_strava:
        description: 'Patch strava'
        required: true
        type: boolean
        default: false
      app_terabox:
        description: 'Patch terabox'
        required: true
        type: boolean
        default: false
      app_turboscan:
        description: 'Patch turboscan'
        required: true
        type: boolean
        default: false
      app_uptodown_store:
        description: 'Patch uptodown-store'
        required: true
        type: boolean
        default: false
      app_wallverse:
        description: 'Patch wallverse'
        required: true
        type: boolean
        default: false
      app_waze:
        description: 'Patch waze'
        required: true
        type: boolean
        default: false
      app_windscribe_vpn:
        description: 'Patch windscribe-vpn'
        required: true
        type: boolean
        default: false
      app_wolfram_alpha:
        description: 'Patch wolfram-alpha'
        required: true
        type: boolean
        default: false
      architecture:
        description: 'Target Architecture'
        required: true
        type: choice
        default: 'arm64-v8a'
        options:
          - arm64-v8a
          - armeabi-v7a
          - x86_64
      version_selection:
        description: 'App Version Selection'
        required: true
        type: choice
        default: 'Latest Recommended'
        options:
          - Latest Recommended
          - Beta
          - Custom
      custom_version:
        description: 'Custom App Version (Required if Custom is selected)'
        required: false
        default: ''
      cli_track:
        description: 'Morphe CLI Track'
        required: true
        type: choice
        default: 'Stable'
        options:
          - Stable
          - Pre-release
      patches_track:
        description: 'Ecosystem Patches Track'
        required: true
        type: choice
        default: 'Stable'
        options:
          - Stable
          - Pre-release
          - Custom Local

jobs:
  execute-patching:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Initialize Java JDK 25
        uses: actions/setup-java@v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'
          
      - name: Initialize Python Environment
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install Dependencies & apkeep
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          wget -q https://github.com/EFForg/apkeep/releases/latest/download/apkeep-x86_64-unknown-linux-gnu -O apkeep
          chmod +x apkeep
          sudo mv apkeep /usr/local/bin/

      - name: Fetch Environment Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.cli_track }}" == "Pre-release" ]; then
            CLI_TAG=$(gh api repos/MorpheApp/morphe-desktop/releases | jq -r '.[0].tag_name')
            gh release download "$CLI_TAG" -R MorpheApp/morphe-desktop --pattern "morphe-desktop-*-all.jar"
          else
            gh release download -R MorpheApp/morphe-desktop --pattern "morphe-desktop-*-all.jar"
          fi
          
          LATEST_JAR=$(ls -v morphe-desktop-*-all.jar | tail -n 1)
          mv "$LATEST_JAR" morphe.jar
          
          REPO_URL="rushiranpise/morphe-patches"
          echo "TARGET_REPO_URL=https://github.com/$REPO_URL" >> $GITHUB_ENV
          
          if [ "${{ github.event.inputs.patches_track }}" == "Custom Local" ]; then
            cp "Custom-Patches/rushiranpise-custom.mpp" patches.mpp
            echo "PATCHES_VERSION=custom-local" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.patches_track }}" == "Pre-release" ]; then
            PATCH_TAG=$(gh api repos/$REPO_URL/releases | jq -r '.[0].tag_name')
            gh release download "$PATCH_TAG" -R $REPO_URL --pattern "*.mpp"
            LATEST_MPP=$(ls -v *.mpp | tail -n 1)
            mv "$LATEST_MPP" patches.mpp
            echo "PATCHES_VERSION=$PATCH_TAG" >> $GITHUB_ENV
          else
            PATCH_TAG=$(gh api repos/$REPO_URL/releases/latest | jq -r '.tag_name')
            gh release download "$PATCH_TAG" -R $REPO_URL --pattern "*.mpp"
            LATEST_MPP=$(ls -v *.mpp | tail -n 1)
            mv "$LATEST_MPP" patches.mpp
            echo "PATCHES_VERSION=$PATCH_TAG" >> $GITHUB_ENV
          fi

      - name: Decode Custom Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > custom.keystore

      # --- CHECKBOX COMBINER ENGINE ---
      - name: Prepare App Selection
        id: prep_apps
        run: |
          APP_LIST=""
          if [ "${{ github.event.inputs.app_1_1_1_1 }}" == "true" ]; then APP_LIST="$APP_LIST,1-1-1-1"; fi
          if [ "${{ github.event.inputs.app_accubattery }}" == "true" ]; then APP_LIST="$APP_LIST,accubattery"; fi
          if [ "${{ github.event.inputs.app_accuweather }}" == "true" ]; then APP_LIST="$APP_LIST,accuweather"; fi
          if [ "${{ github.event.inputs.app_adobe_scan }}" == "true" ]; then APP_LIST="$APP_LIST,adobe-scan"; fi
          if [ "${{ github.event.inputs.app_aida64 }}" == "true" ]; then APP_LIST="$APP_LIST,aida64"; fi
          if [ "${{ github.event.inputs.app_amoledpix }}" == "true" ]; then APP_LIST="$APP_LIST,amoledpix"; fi
          if [ "${{ github.event.inputs.app_ampere }}" == "true" ]; then APP_LIST="$APP_LIST,ampere"; fi
          if [ "${{ github.event.inputs.app_anime_depth }}" == "true" ]; then APP_LIST="$APP_LIST,anime-depth"; fi
          if [ "${{ github.event.inputs.app_apkmirror_installer }}" == "true" ]; then APP_LIST="$APP_LIST,apkmirror-installer"; fi
          if [ "${{ github.event.inputs.app_calm }}" == "true" ]; then APP_LIST="$APP_LIST,calm"; fi
          if [ "${{ github.event.inputs.app_canva }}" == "true" ]; then APP_LIST="$APP_LIST,canva"; fi
          if [ "${{ github.event.inputs.app_colornote }}" == "true" ]; then APP_LIST="$APP_LIST,colornote"; fi
          if [ "${{ github.event.inputs.app_cpu_z }}" == "true" ]; then APP_LIST="$APP_LIST,cpu-z"; fi
          if [ "${{ github.event.inputs.app_electron }}" == "true" ]; then APP_LIST="$APP_LIST,electron"; fi
          if [ "${{ github.event.inputs.app_hola_vpn }}" == "true" ]; then APP_LIST="$APP_LIST,hola-vpn"; fi
          if [ "${{ github.event.inputs.app_http_sniffer }}" == "true" ]; then APP_LIST="$APP_LIST,http-sniffer"; fi
          if [ "${{ github.event.inputs.app_inure }}" == "true" ]; then APP_LIST="$APP_LIST,inure"; fi
          if [ "${{ github.event.inputs.app_kahoot }}" == "true" ]; then APP_LIST="$APP_LIST,kahoot"; fi
          if [ "${{ github.event.inputs.app_kinemaster }}" == "true" ]; then APP_LIST="$APP_LIST,kinemaster"; fi
          if [ "${{ github.event.inputs.app_lark_player }}" == "true" ]; then APP_LIST="$APP_LIST,lark-player"; fi
          if [ "${{ github.event.inputs.app_life360 }}" == "true" ]; then APP_LIST="$APP_LIST,life360"; fi
          if [ "${{ github.event.inputs.app_ml_manager }}" == "true" ]; then APP_LIST="$APP_LIST,ml-manager"; fi
          if [ "${{ github.event.inputs.app_mobioffice }}" == "true" ]; then APP_LIST="$APP_LIST,mobioffice"; fi
          if [ "${{ github.event.inputs.app_netguard }}" == "true" ]; then APP_LIST="$APP_LIST,netguard"; fi
          if [ "${{ github.event.inputs.app_network_guru }}" == "true" ]; then APP_LIST="$APP_LIST,network-guru"; fi
          if [ "${{ github.event.inputs.app_ninja_vpn }}" == "true" ]; then APP_LIST="$APP_LIST,ninja-vpn"; fi
          if [ "${{ github.event.inputs.app_proton_vpn }}" == "true" ]; then APP_LIST="$APP_LIST,proton-vpn"; fi
          if [ "${{ github.event.inputs.app_proxyman }}" == "true" ]; then APP_LIST="$APP_LIST,proxyman"; fi
          if [ "${{ github.event.inputs.app_psiphon_pro }}" == "true" ]; then APP_LIST="$APP_LIST,psiphon-pro"; fi
          if [ "${{ github.event.inputs.app_rar }}" == "true" ]; then APP_LIST="$APP_LIST,rar"; fi
          if [ "${{ github.event.inputs.app_sd_maid_se }}" == "true" ]; then APP_LIST="$APP_LIST,sd-maid-se"; fi
          if [ "${{ github.event.inputs.app_stargazing_hub }}" == "true" ]; then APP_LIST="$APP_LIST,stargazing-hub"; fi
          if [ "${{ github.event.inputs.app_stickerly }}" == "true" ]; then APP_LIST="$APP_LIST,stickerly"; fi
          if [ "${{ github.event.inputs.app_strava }}" == "true" ]; then APP_LIST="$APP_LIST,strava"; fi
          if [ "${{ github.event.inputs.app_terabox }}" == "true" ]; then APP_LIST="$APP_LIST,terabox"; fi
          if [ "${{ github.event.inputs.app_turboscan }}" == "true" ]; then APP_LIST="$APP_LIST,turboscan"; fi
          if [ "${{ github.event.inputs.app_uptodown_store }}" == "true" ]; then APP_LIST="$APP_LIST,uptodown-store"; fi
          if [ "${{ github.event.inputs.app_wallverse }}" == "true" ]; then APP_LIST="$APP_LIST,wallverse"; fi
          if [ "${{ github.event.inputs.app_waze }}" == "true" ]; then APP_LIST="$APP_LIST,waze"; fi
          if [ "${{ github.event.inputs.app_windscribe_vpn }}" == "true" ]; then APP_LIST="$APP_LIST,windscribe-vpn"; fi
          if [ "${{ github.event.inputs.app_wolfram_alpha }}" == "true" ]; then APP_LIST="$APP_LIST,wolfram-alpha"; fi
          
          # Remove leading comma (if any)
          APP_LIST=${APP_LIST#,}
          
          # Prevent error if no application is selected
          if [ -z "$APP_LIST" ]; then
            echo "::error::No applications selected for patching!"
            exit 1
          fi
          
          echo "SELECTED_APPS=$APP_LIST" >> $GITHUB_ENV
          echo "Ready to patch: $APP_LIST"

      - name: Execute Chihafuyu Tool
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_SIGNER_NAME: ${{ secrets.KEYSTORE_SIGNER_NAME }}
        run: |
          python -u chihafuyu_tool.py \
            --ecosystem "rushiranpise" \
            --apps "${{ env.SELECTED_APPS }}" \
            --arch "${{ github.event.inputs.architecture }}" \
            --version-selection "${{ github.event.inputs.version_selection }}" \
            --custom-version "${{ github.event.inputs.custom_version }}" \
            --cli "morphe.jar" \
            --patches "patches.mpp" \
            --patches-version "${{ env.PATCHES_VERSION }}" \
            --repo-url "${{ env.TARGET_REPO_URL }}" \
            --keystore "custom.keystore" \
            --ks-alias "$KEYSTORE_ALIAS" \
            --ks-pass "$KEYSTORE_PASSWORD" \
            --signer "$KEYSTORE_SIGNER_NAME"

      - name: Set Release Tag
        id: vars
        run: echo "DATE_TAG=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v3.0.2
        with:
          tag_name: rushiranpise-${{ env.DATE_TAG }}
          name: Patched Apps - rushiranpise (${{ env.DATE_TAG }})
          body_path: ./rushiranpise/changelog.md
          files: ./rushiranpise/Output/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
